version: 2
jobs:
  build:
  machine:
      environment:
          ANDROID_HOME: /usr/local/android-sdk-linux
      working_directory: ~/CircleCiAndroid
    steps:
      - checkout
      - run:
          name: Assemble & Test (Amazon Flavour)
          command: ./gradlew assembleWithAmazon testWithAmazonDebugUnitTest
          environment:
            TERM: dumb
      - run:
          name: Assemble & Test (Google Flavour)
          command: ./gradlew assembleWithGoogle testWithGoogleDebugUnitTest
          environment:
            TERM: dumb