version: 2
jobs:
  build:
   machine:
      environment:
          ANDROID_HOME: /usr/local/android-sdk-linux
      working_directory: ~/CircleCiAndroid
      dependencies:
          override:
              - echo y | android update sdk --no-ui --all --filter tools,platform-tools,build-tools-26.0.2,android-26,extra-google-m2repository,extra-google-google_play_services,extra-android-support
              - chmod +x gradlew
              - ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
    steps:
      - checkout
      - run:
          name: Assemble & Test (Amazon Flavour)
          command: ./gradlew assembleWithAmazon testWithAmazonDebugUnitTest
          environment:
            TERM: dumb
      - run:
          name: Assemble & Test (Google Flavour)
          command: ./gradlew assembleWithGoogle testWithGoogleDebugUnitTest
          environment:
            TERM: dumb